In [ ]:
e# PANDAS

In [1]:
import pandas as pd

file_ = pd.read_csv('student_data.csv',sep=',')
print(file_.head(8))

   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7
1            4          69            5               3
2           11          60            7               6
3            8          99            9               8
4            5          52            8               6
5            7          40            9              10
6           10          40            4              11
7            3          86            7               3

   assignments_completed  previous_score  exam_score placement_status
0                     10              62      100.00           Placed
1                      8              56      100.00           Placed
2                     10              45      100.00           Placed
3                      4              55       90.17           Placed
4                      8              40       78.82           Placed
5                      0              60       72.33           Placed
6                      9              50       98.12           Placed
7                      7              85      100.00           Placed

In [8]:
import pandas as pd
dct={
    'name':['tom','nick','krish','jack'],
    'age':[20,21,19,18],
    'roll':[1,2,3,4]
}
df=pd.DataFrame(dct)
df=pd.DataFrame(dct,index=['a','b','c','d'])
# df1=pd.DataFrame(dct)
# print(df)
display(df)

    name  age  roll
0    tom   20     1
1   nick   21     2
2  krish   19     3
3   jack   18     4

In [7]:
import pandas as pd
df=pd.read_csv('student_data.csv')
# df.head(3)
# df.tail(3)
# df.shape()
# df.info()
# df.describe()
# df.index()
# df[['study_hours','internet_usage']]
# df[['study_hours','internet_usage']]
# df.iloc[0:5]
df.loc[df['study_hours']==11,['study_hours','sleep_hours']].iloc[4:8]
# iloc works on index
# loc works on tables

     study_hours  sleep_hours
30            11            5
91            11            9
98            11            6
116           11            7

In [19]:
import pandas as pd
df=pd.read_csv('student_data.csv')
# df.loc[df['assignments_completed']==8].iloc[1]
# df[df["assignments_completed"]>3]

# df["age"]=20

# df

# rename columns
df.rename(columns={'assignments_completed':'assign_completed'},inplace=True)
df

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [20]:
import pandas as pd
df=pd.read_csv('student_data.csv')
# Remove rows or column
df.drop(3)
# Remove missing values
df.dropna()
# sort values by column
df.sort_values('assignments_completed')
# sort index
df.sort_index()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed